# Configurations for ktbaileyunc.github.io

title: Kate Bailey
email: ktbailey@unc.edu
description: >- # this means to ignore newlines until "baseurl:"
  I'm an undergraduate studying philosophy and computer science at the University of North Carolina at Chapel Hill.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  ktbaileyunc

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name     : "Kate Bailey"
  avatar   : "/assets/images/kate.jpeg"
  bio      : "Computer science and philosophy student at UNC-Chapel Hill graduating in May 2026."
  location : "Chapel Hill, NC"
  linkedin: "katecbailey"
  github: "ktbaileyunc"

include:
  - _pages
  - assets
exclude:
  - README.md
